### ISSUE TITLE
Support Generating public variables

### ISSUE THREAD

**Issue by mathieutozer** [nesium/xcode-color-assets#5]
I would like to include the generated source in a framework, meaning that the colors need to be exposed publicly. I couldn't figure out how to make this change myself (it should be easy) as I am unfamiliar with the environment.

**Comment by nesium** [comment]
Hey! Sorry for the late reply. I didn't see the notification. I've just pushed a new release (0.5.0) where you can specify `--access public` to set exactly that access level for the generated code.
