### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by youjinp** [nesium/xcode-color-assets#8]
# Compillation Errors
I tried to make some changes but could not compile the code?

Got a bunch of errors with `^^^^ expected usize, found u32` in `lexical-core`, which I think is related to this [issue](https://github.com/rust-lang/rust/issues/81654).

# Nom V7
I then tried to upgrade `nom` to `7.0.0`, but got more errors due to breaking changes with their error management.

# Help
I'm totally new to Rust, just learnt it today.

Can I get some help with the compilation?

Rust version: rustc 1.54.0

---
Thank you

**Comment by nesium** [comment]
Hi. I've updated the dependencies (not to nom 7 though) and it builds for me on Rust 1.54.0 stable. Does that help?

**Comment by youjinp** [comment]
That worked! Thanks again.
